version: 2.1
jobs:
  rust:
      docker:
        - image: ubuntu:22.04
      resource_class: large
      steps:
        - checkout
        - run:
            name: Install Rust
            command: |
              apt-get update
              apt-get install -y curl
              curl https://sh.rustup.rs -sSf | sh -s -- -y
              source $HOME/.cargo/env
              rustup default stable
        - run:
            name: Prepare
            command: |
              apt-get update
              apt-get install -y pkg-config libopusfile-dev llvm-dev libclang-dev clang openssl libssl-dev libasound2-dev libudev-dev libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev ffmpeg libpq-dev upx-ucl
        - run:
            name: Build
            command: |
              source $HOME/.cargo/env
              cd rust
              cargo build --release -p api-bin
              upx --best --lzma target/release/api-bin
              cp target/release/api-bin /tmp/api-bin
        - store_artifacts:
            path: /tmp/api-bin
  client:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: Install Rust
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            source $HOME/.cargo/env
            rustup default stable
      - run:
          name: Prepare
          command: |
            sudo apt-get update
            sudo apt-get install -y pkg-config libopusfile-dev llvm-dev libclang-dev clang openssl libssl-dev libasound2-dev libudev-dev libavutil-dev libavcodec-dev libavformat-dev libpq-dev upx-ucl
      - run:
          name: Build
          command: |
            source $HOME/.cargo/env
            cd rust
            cargo build --release -p myrts-client
            upx --best --lzma target/release/myrts-client
            cp target/release/myrts-client /tmp/myrts-client
      - store_artifacts:
          path: /tmp/myrts-client
workflows:
  build:
    jobs:
      - rust
      - client
