name: API CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                override: true
            - name: Prepare Dependencies
              run: |
                apt-get update
                apt-get install -y pkg-config libopusfile-dev llvm-dev libclang-dev clang openssl libssl-dev libasound2-dev libudev-dev libavutil-dev libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev ffmpeg libpq-dev upx-ucl
            - name: Build
              run: |
                source $HOME/.cargo/env
                cd rust
                cargo build --release -p api-bin
                upx --best --lzma target/release/api-bin
                cp target/release/api-bin /tmp/api-bin
            - name: Store Artifact
              uses: actions/upload-artifact@v4
              with:
                name: api-bin
                path: /tmp/api-bin